### ISSUE TITLE
What's the idea of Complex scopes ? `::` and `:::`

### ISSUE THREAD

**Issue by ZinkLu** [ahopkins/sscopes-python#1]
How to understand the complex scopes? such as `::` or `:::`.

If I define a scope `::delete`, does that mean every income shall pass?

meanwhile , `user:read::delete` only accptes `user:read`, Does it mean complex scopes only accept extractly same part before `::`?

**Comment by ahopkins** [comment]
The double colon (`::`) is a negative, reading from right to left.

Let's take a look at four complex options:

## `::delete`

In this scenario, we are saying something with a `delete` action should not be allowed. But, we have also implicitly set the `global` namespace and required it to be top level. Which is why `user` is the only one that is passing from the below group.

```
user        True
user:read   False
user:delete False
user:       False
:           False
:delete     False
:read       False
```

Because we have implicitly set `global`, it is to be noted that:

```python
>>> sscopes.validate("global", "user")
True
>>> sscopes.validate("global", ":")
False
```

## `:::delete`

This is similar to the first, but should be read as two parts: `:` and `::delete`.

First, let's look at what these cases would look like against `:` as a base.

```
user        True
user:read   True
user:delete True
user:       True
:           True
:delete     True
:read       True
```

In this case everything passes the `:` base.

But, when we remove `delete` actions, we are left with this:

```
user        True
user:read   True
user:delete False
user:       True
:           True
:delete     False
:read       True
```

## `user::delete`

This is identical to the first, because it operates the same way, except we are limiting to only `user` namespace.
```
user        True
user:read   False
user:delete False
user:       False
:           False
:delete     False
:read       False
```

## `foo::delete`

Same as the previous, except with `foobar` namespace.

```
user        False
user:read   False
user:delete False
user:       False
:           False
:delete     False
:read       False
```

---

With that out of the way, let's look at your specific question.

> If I define a scope ::delete, does that mean every income shall pass?

I think this is a somewhat loaded question. Is `::delete` the entire scope, or is it a part of a larger base scope: `foo:bar::delete`. As noted above `::delete` is **VERY** narrow, and almost a bit hacky way of only allowing top level.

> meanwhile , user:read::delete only accptes user:read, Does it mean complex scopes only accept extractly same part before ::?

Yes. It needs to match everything that comes before the negation, but cannot include what is in the negation.

So, given your base `user:read::delete`, we can see our same test looks like this:

```
user        True
user:read   True
user:delete False
user:       False
:           False
:delete     False
:read       False
```

But, what I think really is the differentiating point is that you are removing anything with an explicit `:delete`.

Contrast the two here:

```python
>>> sscopes.validate("user:read::delete", "user:read:delete")
False
>>> sscopes.validate("user:read", "user:read:delete")
True
```

---

Did I answer the question?

**Comment by ZinkLu** [comment]
thanks for the explanation. But I am somehow still confused.

take `user::delete` as an example:

It means something with `user` namespace and do not have `delete` action shall pass right? 

I thought `user` means having all actions in `user` namespace, in this case, `user:delete` is also belongs to `user`.

So `user` or `user:` has no hierarchical relationship with `user:delete`?

**Comment by ahopkins** [comment]
`user` and `user:` are _ALMOST_ the same thing.

The difference is that the first (`user`) is a **TOP LEVEL** action, and the second (`user:`) has all actions for the namespace. [See docs](https://ahopkins.github.io/structured-scopes/makeup/#actions).

Said another way, `user:` means "this scope has any and every possible action assigned to it", but `user` is more like super-access. Therefore, `user:` implicitly includes `user:delete`. But, `user` does not. It matches on the namespace only.

`user::delete` by itself is not a terribly helpful pattern, because it means do not allow anyone in `user` namespace with `delete` action. But, because it does not have any acceptable actions, it really would be useful only to differentiate `user:` from `user`.

**Comment by ZinkLu** [comment]
That is much clear! Thanks for replying!
